"use client";

import { useEffect, useMemo, useState } from "react";
import { Loader2, Save } from "lucide-react";
import { toast } from "sonner";
import LeagueAdminNav from "../_components/LeagueAdminNav";

type Match = { id: string; round_id: string; home_team_id: string; away_team_id: string; scheduled_at: string | null; schedule_version: number; match_status: string; current_result_id: string | null; current_special_outcome_id: string | null };
type Result = { id: string; revision: number; status: string; home_sets_won: number; away_sets_won: number; home_games_won: number; away_games_won: number };
type Data = { phase: { id: string }; teams: Array<{ id: string; name: string }>; rounds: Array<{ id: string; round_number: number }>; matches: Match[]; results: Result[]; sets: Array<{ result_submission_id: string; set_number: number; home_games: number; away_games: number }>; specials: Array<{ id: string; outcome_type: string; decision_reason: string }> };
type Score = { homeGames: string; awayGames: string };

export default function LeagueResultsPage() {
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [filter, setFilter] = useState("missing"); const [selectedId, setSelectedId] = useState("");
  const [scores, setScores] = useState<Score[]>([{ homeGames: "", awayGames: "" }, { homeGames: "", awayGames: "" }, { homeGames: "", awayGames: "" }]); const [reason, setReason] = useState(""); const [winner, setWinner] = useState("");
  const [custom, setCustom] = useState({ counts: true, hp: 0, ap: 0, hs: 0, as: 0, hg: 0, ag: 0 });
  async function load() { setLoading(true); const response = await fetch("/api/admin/monday-league/results", { cache: "no-store" }); const json = await response.json(); if (!response.ok) toast.error(json.error); else setData(json.data); setLoading(false); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const teams = Object.fromEntries((data?.teams ?? []).map((team) => [team.id, team.name])); const rounds = Object.fromEntries((data?.rounds ?? []).map((round) => [round.id, round.round_number]));
  const selected = useMemo(() => data?.matches.find((match) => match.id === selectedId) ?? null, [data, selectedId]); const current = data?.results.find((result) => result.id === selected?.current_result_id) ?? null;
  const visible = useMemo(() => (data?.matches ?? []).filter((match) => filter === "missing" ? ["scheduled", "postponed"].includes(match.match_status) && !match.current_result_id && !match.current_special_outcome_id : filter === "provisional" ? ["submitted", "contested"].includes(match.match_status) : filter === "confirmed" ? match.match_status === "confirmed" && !!match.current_result_id : !!match.current_special_outcome_id || ["postponed", "suspended", "cancelled"].includes(match.match_status)), [data, filter]);
  useEffect(() => { const timer = window.setTimeout(() => { if (!selected) return; const existing = data?.sets.filter((set) => set.result_submission_id === selected.current_result_id) ?? []; setScores([0, 1, 2].map((index) => ({ homeGames: existing[index]?.home_games?.toString() ?? "", awayGames: existing[index]?.away_games?.toString() ?? "" }))); setWinner(selected.home_team_id); setReason(""); }, 0); return () => window.clearTimeout(timer); }, [selected, data]);
  const parsed = scores.filter((score) => score.homeGames !== "" && score.awayGames !== "").map((score) => ({ homeGames: Number(score.homeGames), awayGames: Number(score.awayGames) })); const homeSets = parsed.filter((score) => score.homeGames > score.awayGames).length; const awaySets = parsed.filter((score) => score.awayGames > score.homeGames).length; const validShape = parsed.length >= 2 && Math.max(homeSets, awaySets) === 2 && ((parsed.length === 2 && Math.min(homeSets, awaySets) === 0) || (parsed.length === 3 && Math.min(homeSets, awaySets) === 1));
  async function command(body: Record<string, unknown>) { const response = await fetch("/api/admin/monday-league/results", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); if (!response.ok) toast.error(json.error); else { toast.success("Operazione completata"); await load(); } }
  async function saveResult() { if (!selected || !validShape) return toast.error("Completa un risultato valido 2–0 o 2–1"); if (current && !reason.trim()) return toast.error("Motivazione correzione obbligatoria"); await command({ action: current ? "correct" : "submit", match_id: selected.id, expected_result_id: current?.id, expected_status: current?.status, sets: parsed, reason }); }
  async function special(type: "walkover" | "no_show") { if (!selected || !winner || !reason.trim()) return toast.error("Vincitore e motivazione obbligatori"); const home = winner === selected.home_team_id; await command({ action: "special", match_id: selected.id, expected_result_id: selected.current_result_id, expected_special_outcome_id: selected.current_special_outcome_id, outcome_type: type, winner_team_id: winner, counts_as_played: true, home_points: home ? 3 : 0, away_points: home ? 0 : 3, home_win: home, away_win: !home, home_sets: home ? 2 : 0, away_sets: home ? 0 : 2, home_games: home ? 12 : 0, away_games: home ? 0 : 12, reason }); }
  async function workflow(state: string) { if (!selected || !reason.trim()) return toast.error("Motivazione obbligatoria"); await command({ action: "workflow", match_id: selected.id, expected_schedule_version: selected.schedule_version, state, reason }); }
  async function administrative() { if (!selected || !reason.trim()) return toast.error("Motivazione obbligatoria"); const homeWin = winner === selected.home_team_id; const awayWin = winner === selected.away_team_id; await command({ action: "special", match_id: selected.id, expected_result_id: selected.current_result_id, expected_special_outcome_id: selected.current_special_outcome_id, outcome_type: "administrative", winner_team_id: winner || null, counts_as_played: custom.counts, home_points: custom.hp, away_points: custom.ap, home_win: homeWin, away_win: awayWin, home_sets: custom.hs, away_sets: custom.as, home_games: custom.hg, away_games: custom.ag, reason }); }
  if (loading) return <Loader2 className="animate-spin" />;
  if (!data) return <main style={layout}><h1>Risultati</h1><LeagueAdminNav /><section style={panel}>Genera prima la Fase 1.</section></main>;
  return <main style={layout}><h1 style={{ margin: 0 }}>Risultati Monday League</h1><LeagueAdminNav /><div style={tabs}>{[["missing", "DA INSERIRE"], ["provisional", "PROVVISORI"], ["confirmed", "CONFERMATI"], ["special", "SPECIALI"]].map(([key, label]) => <button key={key} style={{ ...tab, background: filter === key ? "#14b8a6" : "rgba(255,255,255,.06)" }} onClick={() => setFilter(key)}>{label}</button>)}</div>
    <section style={panel}><div style={{ display: "grid", gap: 7 }}>{visible.map((match) => <button key={match.id} style={matchButton} onClick={() => setSelectedId(match.id)}>G{rounds[match.round_id]} · {teams[match.home_team_id]} — {teams[match.away_team_id]} · {match.match_status}</button>)}</div>{visible.length === 0 && <p style={muted}>Nessuna partita in questa vista.</p>}</section>
    {selected && <><section style={panel}><h2 style={{ marginTop: 0 }}>{teams[selected.home_team_id]} vs {teams[selected.away_team_id]}</h2><p style={muted}>Giornata {rounds[selected.round_id]} · {selected.match_status} {current ? `· revisione ${current.revision}` : ""}</p><div style={{ display: "grid", gap: 8 }}>{scores.map((score, index) => <div key={index} style={scoreRow}><strong>Set {index + 1}</strong><input type="number" min="0" max="7" style={input} value={score.homeGames} onChange={(event) => setScores((items) => items.map((item, i) => i === index ? { ...item, homeGames: event.target.value } : item))} /><span>—</span><input type="number" min="0" max="7" style={input} value={score.awayGames} onChange={(event) => setScores((items) => items.map((item, i) => i === index ? { ...item, awayGames: event.target.value } : item))} /></div>)}</div><p style={validShape ? good : muted}>{validShape ? `Anteprima: ${homeSets}–${awaySets}; punti ${homeSets === 2 && awaySets === 0 ? "3–0" : homeSets === 2 ? "2–1" : homeSets === 0 ? "0–3" : "1–2"}` : "Inserisci due o tre set legali."}</p>{current && <textarea style={input} placeholder="Motivazione correzione obbligatoria" value={reason} onChange={(event) => setReason(event.target.value)} />}<button style={button} onClick={saveResult}><Save size={16} />{current ? "Salva correzione" : "Salva risultato provvisorio"}</button>{current && current.status !== "confirmed" && <button style={button} onClick={() => command({ action: "confirm", match_id: selected.id, expected_result_id: current.id })}>Conferma risultato</button>}</section>
      <section style={panel}><h2 style={{ marginTop: 0 }}>Esito speciale</h2><select style={input} value={winner} onChange={(event) => setWinner(event.target.value)}><option value="">Nessun vincitore</option><option value={selected.home_team_id}>{teams[selected.home_team_id]}</option><option value={selected.away_team_id}>{teams[selected.away_team_id]}</option></select><textarea style={input} placeholder="Motivazione decisione" value={reason} onChange={(event) => setReason(event.target.value)} /><div style={tabs}><button style={button} onClick={() => special("walkover")}>Vittoria a tavolino · 3 pt, 2–0 set, 12–0 game</button><button style={button} onClick={() => special("no_show")}>No-show</button><button style={button} onClick={() => workflow("postponed")}>Rinvia partita</button><button style={button} onClick={() => workflow("suspended")}>Sospendi partita</button><button style={button} onClick={() => workflow("cancelled")}>Annulla partita</button></div><details style={{ marginTop: 14 }}><summary><strong>Decisione amministrativa avanzata</strong></summary><p style={{ color: "#fbbf24" }}>Attenzione: questi valori incidono direttamente sulla classifica e sono validati dal database.</p><label><input type="checkbox" checked={custom.counts} onChange={(event) => setCustom({ ...custom, counts: event.target.checked })} /> Conta come giocata</label><div style={customGrid}>{[["PT casa", "hp"], ["PT ospite", "ap"], ["Set casa", "hs"], ["Set ospite", "as"], ["Game casa", "hg"], ["Game ospite", "ag"]].map(([label, key]) => <label key={key}>{label}<input type="number" min="0" style={input} value={custom[key as keyof typeof custom] as number} onChange={(event) => setCustom({ ...custom, [key]: Number(event.target.value) })} /></label>)}</div><button style={button} onClick={administrative}>Applica decisione amministrativa</button></details></section></>}
  </main>;
}
const layout: React.CSSProperties = { display: "grid", gap: 18, color: "#0f172a" }; const panel: React.CSSProperties = { padding: 18, borderRadius: 18, background: "#fff", border: "1px solid #e2e8f0", boxShadow: "0 8px 24px rgba(15,23,42,.06)" }; const muted: React.CSSProperties = { color: "#64748b" }; const good: React.CSSProperties = { color: "#0f766e", fontWeight: 800 }; const tabs: React.CSSProperties = { display: "flex", flexWrap: "wrap", gap: 8 }; const tab: React.CSSProperties = { padding: "9px 12px", border: 0, borderRadius: 10, color: "#0f172a", fontWeight: 800 }; const matchButton: React.CSSProperties = { textAlign: "left", padding: 11, borderRadius: 10, border: "1px solid #e2e8f0", background: "#f8fafc", color: "#0f172a" }; const scoreRow: React.CSSProperties = { display: "grid", gridTemplateColumns: "80px 90px 20px 90px", gap: 8, alignItems: "center" }; const input: React.CSSProperties = { padding: 9, borderRadius: 9, border: "1px solid #cbd5e1", background: "#fff", color: "#0f172a", width: "100%", marginTop: 5 }; const button: React.CSSProperties = { display: "inline-flex", alignItems: "center", gap: 6, padding: "9px 12px", marginTop: 10, marginRight: 7, border: 0, borderRadius: 10, background: "#14b8a6", color: "#042f2e", fontWeight: 900 }; const customGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(120px,1fr))", gap: 8, marginTop: 10 };
