import type { BaraondaCategory, BaraondaFormula } from "../domain/types";

export type BaraondaCardPreviewDataEntry = {
  category: BaraondaCategory;
  players: number;
  formula: BaraondaFormula;
  courts: number;
  matchesPerPlayer: number;
  totalMatches: number;
  totalTurns: number;
  valid: boolean;
  summary: string;
};

export const BARAONDA_CARD_PREVIEW_DATA: BaraondaCardPreviewDataEntry[] = [
  {
    "category": "libero",
    "players": 4,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 3,
    "totalMatches": 3,
    "totalTurns": 3,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 5,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 5,
    "totalTurns": 5,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 6,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 9,
    "totalTurns": 9,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 6,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 6,
    "totalTurns": 6,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 7,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 14,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 7,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 7,
    "totalTurns": 7,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 8,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 7,
    "totalMatches": 14,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 8,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 7,
    "totalMatches": 14,
    "totalTurns": 7,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 8,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 8,
    "totalTurns": 8,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 8,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 8,
    "totalTurns": 8,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 9,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 18,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 9,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 18,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 9,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 9,
    "totalTurns": 9,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 9,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 9,
    "totalTurns": 8,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 10,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 20,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 10,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 20,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 10,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 10,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 10,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 10,
    "totalTurns": 7,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 11,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 22,
    "totalTurns": 22,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 11,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 22,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 11,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 12,
    "totalMatches": 33,
    "totalTurns": 33,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 11,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 12,
    "totalMatches": 33,
    "totalTurns": 17,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 11,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 11,
    "totalTurns": 11,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 11,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 11,
    "totalTurns": 6,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 24,
    "totalTurns": 24,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 24,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 24,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 10,
    "totalMatches": 30,
    "totalTurns": 30,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 10,
    "totalMatches": 30,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 10,
    "totalMatches": 30,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 18,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 18,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 12,
    "formula": "snella",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 18,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 26,
    "totalTurns": 26,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 26,
    "totalTurns": 13,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 26,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 12,
    "totalMatches": 39,
    "totalTurns": 39,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 12,
    "totalMatches": 39,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 12,
    "totalMatches": 39,
    "totalTurns": 17,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 16,
    "totalMatches": 52,
    "totalTurns": 52,
    "valid": true,
    "summary": "Schedule non valida: 0 errori, 2 warning"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 16,
    "totalMatches": 52,
    "totalTurns": 26,
    "valid": true,
    "summary": "Schedule non valida: 0 errori, 2 warning"
  },
  {
    "category": "libero",
    "players": 13,
    "formula": "maratona",
    "courts": 3,
    "matchesPerPlayer": 16,
    "totalMatches": 52,
    "totalTurns": 21,
    "valid": true,
    "summary": "Schedule non valida: 0 errori, 2 warning"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 28,
    "totalTurns": 28,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 28,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 28,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 10,
    "totalMatches": 35,
    "totalTurns": 35,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 10,
    "totalMatches": 35,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 10,
    "totalMatches": 35,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 21,
    "totalTurns": 21,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 21,
    "totalTurns": 11,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 14,
    "formula": "snella",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 21,
    "totalTurns": 9,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 30,
    "totalTurns": 30,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 30,
    "totalTurns": 15,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 30,
    "totalTurns": 13,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 12,
    "totalMatches": 45,
    "totalTurns": 45,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 12,
    "totalMatches": 45,
    "totalTurns": 23,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 12,
    "totalMatches": 45,
    "totalTurns": 17,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 15,
    "totalTurns": 15,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 15,
    "totalTurns": 8,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 15,
    "formula": "snella",
    "courts": 3,
    "matchesPerPlayer": 4,
    "totalMatches": 15,
    "totalTurns": 6,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 32,
    "totalTurns": 32,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 32,
    "totalTurns": 16,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 32,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 10,
    "totalMatches": 40,
    "totalTurns": 40,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 10,
    "totalMatches": 40,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 10,
    "totalMatches": 40,
    "totalTurns": 15,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 24,
    "totalTurns": 24,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 24,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 16,
    "formula": "snella",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 24,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 34,
    "totalTurns": 34,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 34,
    "totalTurns": 17,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 34,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 12,
    "totalMatches": 51,
    "totalTurns": 51,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 12,
    "totalMatches": 51,
    "totalTurns": 26,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 12,
    "totalMatches": 51,
    "totalTurns": 19,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 16,
    "totalMatches": 68,
    "totalTurns": 68,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 16,
    "totalMatches": 68,
    "totalTurns": 34,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 17,
    "formula": "maratona",
    "courts": 3,
    "matchesPerPlayer": 16,
    "totalMatches": 68,
    "totalTurns": 24,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 36,
    "totalTurns": 36,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 36,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 36,
    "totalTurns": 13,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 10,
    "totalMatches": 45,
    "totalTurns": 45,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 10,
    "totalMatches": 45,
    "totalTurns": 23,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 10,
    "totalMatches": 45,
    "totalTurns": 16,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 12,
    "totalMatches": 54,
    "totalTurns": 54,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 12,
    "totalMatches": 54,
    "totalTurns": 27,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 18,
    "formula": "maratona",
    "courts": 3,
    "matchesPerPlayer": 12,
    "totalMatches": 54,
    "totalTurns": 19,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 38,
    "totalTurns": 38,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 38,
    "totalTurns": 19,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 38,
    "totalTurns": 13,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 12,
    "totalMatches": 57,
    "totalTurns": 57,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 12,
    "totalMatches": 57,
    "totalTurns": 29,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 12,
    "totalMatches": 57,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 16,
    "totalMatches": 76,
    "totalTurns": 76,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 16,
    "totalMatches": 76,
    "totalTurns": 38,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 19,
    "formula": "maratona",
    "courts": 3,
    "matchesPerPlayer": 16,
    "totalMatches": 76,
    "totalTurns": 26,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 40,
    "totalTurns": 40,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 40,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 40,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 10,
    "totalMatches": 50,
    "totalTurns": 50,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 10,
    "totalMatches": 50,
    "totalTurns": 25,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 10,
    "totalMatches": 50,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 12,
    "totalMatches": 60,
    "totalTurns": 60,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 12,
    "totalMatches": 60,
    "totalTurns": 30,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "libero",
    "players": 20,
    "formula": "maratona",
    "courts": 3,
    "matchesPerPlayer": 12,
    "totalMatches": 60,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 8,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 8,
    "totalTurns": 8,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 8,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 8,
    "totalTurns": 4,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 10,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 15,
    "totalTurns": 15,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 10,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 15,
    "totalTurns": 8,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 12,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 18,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 12,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 18,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 12,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 18,
    "totalTurns": 9,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 21,
    "totalTurns": 21,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 21,
    "totalTurns": 11,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 21,
    "totalTurns": 9,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 28,
    "totalTurns": 28,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 28,
    "totalTurns": 15,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 28,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 14,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 14,
    "totalTurns": 7,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 14,
    "formula": "snella",
    "courts": 3,
    "matchesPerPlayer": 4,
    "totalMatches": 14,
    "totalTurns": 7,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 24,
    "totalTurns": 24,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 24,
    "totalTurns": 12,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 24,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 32,
    "totalTurns": 32,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 32,
    "totalTurns": 17,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 32,
    "totalTurns": 13,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "snella",
    "courts": 1,
    "matchesPerPlayer": 4,
    "totalMatches": 16,
    "totalTurns": 16,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "snella",
    "courts": 2,
    "matchesPerPlayer": 4,
    "totalMatches": 16,
    "totalTurns": 8,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 16,
    "formula": "snella",
    "courts": 3,
    "matchesPerPlayer": 4,
    "totalMatches": 16,
    "totalTurns": 7,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 27,
    "totalTurns": 27,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 27,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 27,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 36,
    "totalTurns": 36,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 36,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 36,
    "totalTurns": 13,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 10,
    "totalMatches": 45,
    "totalTurns": 45,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 10,
    "totalMatches": 45,
    "totalTurns": 23,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 18,
    "formula": "maratona",
    "courts": 3,
    "matchesPerPlayer": 10,
    "totalMatches": 45,
    "totalTurns": 16,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "bilanciata",
    "courts": 1,
    "matchesPerPlayer": 6,
    "totalMatches": 30,
    "totalTurns": 30,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "bilanciata",
    "courts": 2,
    "matchesPerPlayer": 6,
    "totalMatches": 30,
    "totalTurns": 15,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "bilanciata",
    "courts": 3,
    "matchesPerPlayer": 6,
    "totalMatches": 30,
    "totalTurns": 10,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "estesa",
    "courts": 1,
    "matchesPerPlayer": 8,
    "totalMatches": 40,
    "totalTurns": 40,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "estesa",
    "courts": 2,
    "matchesPerPlayer": 8,
    "totalMatches": 40,
    "totalTurns": 20,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "estesa",
    "courts": 3,
    "matchesPerPlayer": 8,
    "totalMatches": 40,
    "totalTurns": 14,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "maratona",
    "courts": 1,
    "matchesPerPlayer": 10,
    "totalMatches": 50,
    "totalTurns": 50,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "maratona",
    "courts": 2,
    "matchesPerPlayer": 10,
    "totalMatches": 50,
    "totalTurns": 25,
    "valid": true,
    "summary": "Schedule valida"
  },
  {
    "category": "misto",
    "players": 20,
    "formula": "maratona",
    "courts": 3,
    "matchesPerPlayer": 10,
    "totalMatches": 50,
    "totalTurns": 18,
    "valid": true,
    "summary": "Schedule valida"
  }
] as const;
