"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Loader2, Save } from "lucide-react";
import { toast } from "sonner";
import LeagueAdminNav from "../_components/LeagueAdminNav";
import { generateWeeklyMondayDates, isIsoMonday } from "@/lib/monday-league/scheduling";
import styles from "./calendar.module.css";

type Round = { id: string; round_number: number; play_date: string | null; status: string; schedule_version: number };
type Match = { id: string; round_id: string; home_team_id: string; away_team_id: string; venue_id: string | null; scheduled_at: string | null; match_status: string };
type Venue = { id: string; code: string; name: string; league_venue_slots: Array<{ id: string; local_time: string; is_active: boolean }> };
type Data = { phase: { id: string; status: string; name: string }; phases: Array<{ id: string; name: string; code: string }>; rounds: Round[]; matches: Match[]; teams: Array<{ id: string; name: string }>; venues: Venue[] };

export default function LeagueCalendarPage() {
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true);
  const [firstMonday, setFirstMonday] = useState(""); const [dates, setDates] = useState<Record<string, string>>( {} );
  const [selectedId, setSelectedId] = useState(""); const [assignments, setAssignments] = useState<Record<string, string>>( {} );
  async function load(phaseId?: string) { setLoading(true); const response = await fetch(`/api/admin/monday-league/schedule${phaseId ? `?phase=${encodeURIComponent(phaseId)}` : ""}`, { cache: "no-store" }); const json = await response.json(); if (!response.ok) toast.error(json.error); else { setData(json.data); setDates(Object.fromEntries((json.data?.rounds ?? []).map((round: Round) => [round.id, round.play_date ?? ""]))); setSelectedId(json.data?.rounds?.[0]?.id || ""); } setLoading(false); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const selected = useMemo(() => data?.rounds.find((round) => round.id === selectedId) ?? null, [data, selectedId]);
  const roundMatches = useMemo(() => data?.matches.filter((match) => match.round_id === selectedId) ?? [], [data, selectedId]);
  const teamNames = Object.fromEntries((data?.teams ?? []).map((team) => [team.id, team.name]));
  const slots = useMemo(() => (data?.venues ?? []).flatMap((venue) => venue.league_venue_slots.filter((slot) => slot.is_active).map((slot) => ({ ...slot, venue_id: venue.id, label: `${venue.name} ${slot.local_time.slice(0, 5)}` }))).sort((a, b) => a.label.localeCompare(b.label)), [data]);
  useEffect(() => { const timer = window.setTimeout(() => { if (!selected) return; const next: Record<string, string> = {}; for (const match of roundMatches) { if (!match.venue_id || !match.scheduled_at) { next[match.id] = ""; continue; } const time = new Intl.DateTimeFormat("it-IT", { timeZone: "Europe/Rome", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(match.scheduled_at)); next[match.id] = slots.find((slot) => slot.venue_id === match.venue_id && slot.local_time.startsWith(time))?.id ?? ""; } setAssignments(next); }, 0); return () => window.clearTimeout(timer); }, [roundMatches, selected, slots]);
  function propose() { try { if (!data) return; const proposal = generateWeeklyMondayDates(data.rounds, firstMonday); setDates(Object.fromEntries(proposal.map((item) => [item.roundId, item.playDate]))); } catch (error) { toast.error(error instanceof Error ? error.message : "Data non valida"); } }
  async function saveDates() { if (!data) return; const response = await fetch("/api/admin/monday-league/round-dates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phase_id: data.phase.id, dates: data.rounds.map((round) => ({ roundId: round.id, expectedScheduleVersion: round.schedule_version, playDate: dates[round.id] ?? "" })) }) }); const json = await response.json(); if (!response.ok) toast.error(json.error); else { toast.success("Date salvate atomicamente"); await load(); } }
  async function saveSchedule() { if (!selected) return; const playDate = dates[selected.id] ?? ""; if (!isIsoMonday(playDate)) return toast.error("Seleziona un lunedì"); const response = await fetch("/api/admin/monday-league/schedule/round", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ round_id: selected.id, expected_schedule_version: selected.schedule_version, play_date: playDate, assignments: roundMatches.map((match) => ({ matchId: match.id, venueSlotId: assignments[match.id] || null })) }) }); const json = await response.json(); if (!response.ok) toast.error(json.error); else { toast.success("Giornata salvata"); await load(); } }
  if (loading) return <Loader2 className="animate-spin" />;
  if (!data) return <main className={styles.layout} style={layout}><h1>Calendario</h1><LeagueAdminNav /><section className={styles.panel} style={panel}>Genera prima la Fase 1.</section></main>;
  return <main className={styles.layout} style={layout}><h1 className={styles.heading} style={{ margin: 0 }}>Calendario Monday League</h1><LeagueAdminNav />
    <section className={styles.panel} style={panel}><h2 style={{ marginTop: 0 }}>Fase</h2><select className={styles.control} style={input} value={data.phase.id} onChange={(event)=>void load(event.target.value)}>{data.phases.map(phase=><option key={phase.id} value={phase.id}>{phase.name}</option>)}</select></section>
    <section className={styles.panel} style={panel}><h2 className={styles.heading} style={{ marginTop: 0 }}>Genera date settimanali · {data.phase.name}</h2><p style={muted}>Le proposte restano modificabili e non vengono persistite fino alla conferma.</p><div className={styles.actionRow} style={row}><input className={styles.control} type="date" value={firstMonday} onChange={(event) => setFirstMonday(event.target.value)} style={input} /><button className={styles.actionButton} style={button} onClick={propose}><CalendarDays size={16} />Genera date settimanali</button></div><div style={{ display: "grid", gap: 7, marginTop: 12 }}>{data.rounds.map((round) => <label key={round.id} className={styles.dateRow}><strong>Giornata {round.round_number}</strong><input className={styles.control} type="date" value={dates[round.id] ?? ""} onChange={(event) => setDates((current) => ({ ...current, [round.id]: event.target.value }))} style={input} /></label>)}</div><button className={styles.actionButton} style={button} onClick={saveDates}><Save size={16} />Conferma date</button></section>
    <section className={styles.panel} style={panel}><h2 className={styles.heading} style={{ marginTop: 0 }}>Programmazione giornata</h2><select className={styles.control} style={input} value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{data.rounds.map((round) => <option key={round.id} value={round.id}>Giornata {round.round_number} · {round.play_date || "senza data"} · {round.status}</option>)}</select>{selected && <><label className={styles.dateRow}><strong>Data lunedì</strong><input className={styles.control} type="date" style={input} value={dates[selected.id] ?? ""} onChange={(event) => setDates((current) => ({ ...current, [selected.id]: event.target.value }))} /></label><h3>Partite e slot ufficiali</h3><div style={{ display: "grid", gap: 10 }}>{roundMatches.map((match) => <div key={match.id} className={styles.matchRow}><div className={styles.matchLabel}><strong>{teamNames[match.home_team_id]} — {teamNames[match.away_team_id]}</strong><div style={muted}>{match.match_status}</div></div><select className={styles.control} style={input} value={assignments[match.id] ?? ""} onChange={(event) => setAssignments((current) => ({ ...current, [match.id]: event.target.value }))}><option value="">Non programmata</option>{slots.map((slot) => <option key={slot.id} value={slot.id}>{slot.label}</option>)}</select></div>)}</div><button className={styles.actionButton} style={button} onClick={saveSchedule}><Save size={16} />Salva giornata atomicamente</button></>}</section>
  </main>;
}
const layout: React.CSSProperties = { display: "grid", gap: 18, color: "#0f172a" }; const panel: React.CSSProperties = { padding: 18, borderRadius: 18, background: "#fff", border: "1px solid #e2e8f0", boxShadow: "0 8px 24px rgba(15,23,42,.06)" }; const muted: React.CSSProperties = { color: "#64748b" }; const row: React.CSSProperties = { display: "flex", gap: 10, flexWrap: "wrap" }; const input: React.CSSProperties = { padding: 10, borderRadius: 10, border: "1px solid #cbd5e1", background: "#fff", color: "#0f172a", width: "100%" }; const button: React.CSSProperties = { marginTop: 10, display: "inline-flex", alignItems: "center", gap: 7, padding: "10px 14px", border: 0, borderRadius: 11, background: "#14b8a6", color: "#042f2e", fontWeight: 900 };
